server_events:
  server_events/shutdown: "Server shutdown [deprecated]"
  server_events/retire: "Server retired"
  server_events/move: "Server moved to another group"
  server_events/unretire: "Server un-retired"
  server_events/delete: "Server deleted"
  server_events/restart: "Server restarted"
  server_events/deactivate: "Server deactivated"
  server_events/reactivate: "Server reactivated"
  server_events/missing: "Server missing"
  server_events/ip_address_changed: "Server IP address changed"
  server_events/new_server: "New server"
  server_events/daemon_version_change: "Daemon version changed"
  server_events/vulnerable_software_package_found: "Vulnerable software package found"
  server_events/account_created: "Local account created"
  server_events/account_deleted: "Local account deleted"
  server_events/agent_key_regenerated: "Agent registration key regenerated"
  server_events/daemon_settings_modified: "Daemon settings modified"
  server_events/daemon_retirement_timeout_modified: "Automatic Server Retirement Setting Modified"
  server_events/multiple_root_accounts: "Multiple root accounts detected (Linux Only)"
  server_events/duplicate_uid_accounts: "Multiple accounts detected with same UID (Linux Only)"
  server_events/local_account_create_request: "Local account creation requested"
  server_events/local_account_activate_request: "Local account activation requested"
  server_events/local_account_deactivate_request: "Local account deactivation requested"
  server_events/local_account_update_request: "Local account modification requested"
  server_events/local_account_update_ssh_keys_request: "Local account ssh keys update requested"
  server_events/sam_scan_requested: "Server Account Scan Requested"
  server_events/lids_rule_failed: "Log-based intrusion detection rule matched"
  server_events/lids_policy_created: "Log-based intrusion detection policy created"
  server_events/lids_policy_deleted: "Log-based intrusion detection policy deleted"
  server_events/lids_policy_modified: "Log-based intrusion detection policy modified"
  server_events/lids_policy_exported: "Log-based intrusion detection policy exported"
  server_events/key_expired: "Key expired"
  server_events/key_deleted: "Key deleted"
  server_events/key_created: "Key created"
  server_events/key_status_updated: "Key status updated"
  server_events/key_request_success: "Key request success"
  server_events/key_delivery_success: "Key delivery success"
  server_events/km_policy_created: "Key management policy created"
  server_events/km_policy_deleted: "Key management policy deleted"
  server_events/km_policy_assigned: "Key management policy assigned"
  server_events/km_policy_unassigned: "Key management policy unassigned"
  server_events/km_policy_modified: "Key management policy modified"
  server_events/firewall_policy_created: "Halo firewall policy created"
  server_events/firewall_policy_modified: "Halo firewall policy modified"
  server_events/firewall_policy_deleted: "Halo firewall policy deleted"
  server_events/firewall_policy_assigned: "Halo firewall policy assigned"
  server_events/firewall_policy_unassigned: "Halo firewall policy unassigned"
  server_events/firewall_modified: "Server firewall modified"
  server_events/firewall_restore_requested: "Server firewall restore requested"
  server_events/firewall_service_added: "Network service added"
  server_events/firewall_service_modified: "Network service modified"
  server_events/firewall_service_deleted: "Network service deleted"
  server_events/compromised: "Daemon compromised"
  server_events/sca_rule_failed: "Configuration rule matched"
  server_events/sca_policy_created: "Configuration policy created"
  server_events/sca_policy_assigned: "Configuration policy assigned"
  server_events/sca_policy_unassigned: "Configuration policy unassigned"
  server_events/sca_policy_modified: "Configuration policy modified"
  server_events/sca_policy_deleted: "Configuration policy deleted"
  server_events/sca_policy_exported: "Configuration policy exported"
  server_events/sca_policy_imported: "Configuration policy imported"
  server_events/ghostport_success: "GhostPorts login success"
  server_events/ghostport_failure: "GhostPorts login failure"
  server_events/ghostport_provisioning: "GhostPorts provisioning"
  server_events/ghostport_close: "GhostPorts session close"
  server_events/api_client_created: "API Key Created"
  server_events/api_client_updated: "API Key Modified"
  server_events/api_client_deleted: "API Key Deleted"
  server_events/api_client_secret_viewed: "API Secret Key Viewed"
  server_events/user_deactivated: Halo User Deactivated
  server_events/user_deleted: Halo user deleted
  server_events/user_invited: Halo User Added
  server_events/user_modified: Halo User Modified
  server_events/mfa_provisioning: Halo User Authentication Modified
  server_events/session_timeout_modified: Halo session timeout modified
  server_events/user_reactivated: Halo User Reactivated
  server_events/user_reinvited: Halo User Re-added
  server_events/password_config_changed: "Halo password authentication settings modified"
  server_events/authentication_settings_modified: "Halo authentication settings modified"
  server_events/password_changed: Halo password changed
  server_events/password_recovery_requested: Halo password recovery requested
  server_events/password_recovery_success: Halo password recovery success
  server_events/password_recovery_request_failed: Halo password recovery failed
  server_events/activation_link_failed: Halo user activation failed
  server_events/password_recovery_request_failed: Halo password recovery request failed
  server_events/account_locked: Halo user account locked
  server_events/account_unlocked: Halo user account unlocked
  server_events/api_login_success: "Halo API authentication success"
  server_events/api_login_failure: "Halo API authentication failure"
  server_events/login_success: Halo login success
  server_events/login_failure: Halo login failure
  server_events/logout: Halo logout
  server_events/session_timeout: Halo session timeout
  server_events/sms_phone_number_verified: SMS phone number verified
  server_events/authorized_ips_modified: "Authorized IPs modified"
  server_events/portal_audit_policy_modified: "Portal audit policy modified"
  server_events/master_account_linked: "Master account linked"
  server_events/lids_policy_assigned: "Log-based intrusion detection policy assigned"
  server_events/lids_policy_unassigned: "Log-based intrusion detection policy unassigned"
  server_events/lids_scan_enabled: "Log-based intrusion detection enabled"
  server_events/lids_scan_disabled: "Log-based intrusion detection disabled"
  server_events/cve_exception_created: "Software vulnerability exception created"
  server_events/cve_exception_updated: "Software vulnerability exception updated"
  server_events/cve_exception_deleted: "Software vulnerability exception deleted"
  server_events/cve_exception_expired: "Software vulnerability exception expired"
  server_events/server_group_moved: "Server group moved"
  server_events/server_group_added: "Server group added"
  server_events/server_group_deleted: "Server group deleted"
  server_events/issue_resolved: "Issue resolved"
  fim/server_events/signature_changed: "File Integrity object signature changed"
  fim/server_events/target_integrity_changed: "File Integrity change detected"
  fim/server_events/missing: "File Integrity object missing"
  fim/server_events/added: "File Integrity object added"
  fim/server_events/baseline: "File Integrity baseline"
  fim/server_events/re_baseline: "File Integrity re-baseline"
  fim/server_events/baseline_failed: "File Integrity baseline failed"
  fim/server_events/baseline_expired: "File Integrity baseline expired"
  fim/server_events/baseline_deleted: "File Integrity baseline deleted"
  fim/server_events/baseline_invalid: File integrity baseline invalid
  fim/server_events/exception_created: "File Integrity exception created"
  fim/server_events/exception_deleted: "File Integrity exception deleted"
  fim/server_events/exception_expired: "File Integrity exception expired"
  fim/server_events/policy_assigned: File Integrity policy assigned
  fim/server_events/policy_created: File Integrity policy created
  fim/server_events/policy_deleted: File Integrity policy deleted
  fim/server_events/policy_modified: File Integrity policy modified
  fim/server_events/policy_unassigned: File Integrity policy unassigned
  fim/server_events/scan_requested: File Integrity scan requested
  fim/server_events/scan_failed: File integrity scan failed
  fim/server_events/policy_exported: File Integrity policy exported
  fim/server_events/policy_imported: File Integrity policy imported
  fim/server_events/scan_disabled: Automatic file integrity scanning disabled
  fim/server_events/scan_enabled: Automatic file integrity scanning enabled
  fim/server_events/scan_modified: Automatic file integrity scan schedule modified